### PR TITLE
Add root function to scicalc

### PR DESCRIPTION
**Pull request by sharpc42**
@bwilson3853 could you look at this?

### CODE REVIEW

**Comment by bwilson3853** [comment]
Sure! I like how you initialized y=2 because that's probably commonly used. Also it was documented well. But I noticed you added `sqrt` in addition to `root` into the operator dictionary. Maybe that was a mistake!

**Comment by sharpc42** [comment]
I had a thought was that people looking to call a square root directly might think to call sqrt (since it seems a common abbreviation), in which case they'd only provide the value to put "under the radical" and the default root-2 value kicks in. But it seems that doesn't work calling from the command line. I'll take it out for now.

**Comment by sharpc42** [comment]
There we go. @bwilson3853 anything else?

**Comment by bwilson3853** [comment]
Seems great to me!

**Pull request merged**
